### ISSUE TITLE
Device is paired, but says it is disconnected

### ISSUE THREAD

**Issue by seanbperiod** [DigitaSecurity/DND-Issues#11]
My iphone is paired to my laptop, but immediately shows "Laptop Disconnected." How do I fix this? 

I have Little Snitch running, but with full permissions for DND apps, and a hosts file that blocks common ad/tracking domains. 

I also have had similar issues with Prey.

**Comment by josh-stein** [comment]
@seanbperiod Is this immediately following a lid open alert?

**Comment by josh-stein** [comment]
No problem. For completeness, by design the laptop will only connect following an alert and stay connected for 5 minutes listening for active response actions.

**Comment by seanbperiod** [comment]
Nice! I appreciate the quick and thorough support ;)
