### ISSUE TITLE
iOs App hangs on "Register for notifications"

### ISSUE THREAD

**Issue by FreakX23** [DigitaSecurity/DND-Issues#12]
Tried to bind the iOs Device several Times, always hangs on the same Step
![img_0325](https://user-images.githubusercontent.com/24979542/39320815-8a5c92be-4985-11e8-9931-de837bd224d7.png) Tried on the latest iOs release 11.3.1 as well as the latest beta 11.4. Mac OS is the latest Dev Beta.

**Comment by josh-stein** [comment]
First, thank you for your interest in DND.  We appreciate the feedback and hope to troubleshoot this issue quickly.

Please send a follow up email with some debugging information to dnd@digitasecurity.com

Please include:
* Confirmation that you are running v1.0.2 of the macOS app found on the top of the preferences pane * Confirmation that you are running v1.0 (build 620) of the iOS app found on the bottom of "About" page
* The start of your device identifier found in Settings->Info->iPhone Device Token in the iOS DND App
* The preferences (.plist) and DND.log files found in /Library/DigitaSecurity/DND
 
This should give us a good head start on identifying this issue.

Thanks again,
Digita Security Team

**Comment by FreakX23** [comment]
Thanks to the awesome Support everything is solved now. Thanks a lot.
