### ISSUE TITLE
Option/Ability for locked mac detection

### ISSUE THREAD

**Issue by noaht8um** [DigitaSecurity/DND-Issues#27]
This may be a misunderstanding on my part of how the tool works in general.
I assume it's something like (simplified):

1. DND running on Mac
2. DND detects laptop close event
3. DND alerts iPhone
4. User decision
5. Repeat

Now for me, I often leave my mac running but lock the screen before I walk away (control-command-q). Again, I could be totally wrong on the flow of DND, but what if it could detect laptop close and laptop lock/screensaver. I'm no Apple developer, but Apple has the "[CGSessionCopyCurrentDictionary](https://developer.apple.com/documentation/coregraphics/quartz_display_services#//apple_ref/c/func/CGSessionCopyCurrentDictionary)" API that gives access to computer lock status. Then it could be like:

1. DND running on Mac
2. DND detects laptop close event **OR** lock **OR** screensaver
3. DND alerts iPhone
4. User decision
5. Repeat

I'll clone the repo and start looking myself, but I just think this would be a nice feature. Thanks!

**Comment by josh-stein** [comment]
@noaht8um, 

First, thanks for the feedback. You are mostly correct. Simply switch "laptop close" for "laptop open" and you've got it nailed.

As for your suggestion, I believe we have this captured in https://github.com/DigitaSecurity/DND-Issues/issues/3 (unlock, dismiss screensaver, etc are other variations of wake from sleep, login, etc) and this is on slate for version 2.0. 

If you don't feel we've properly captured your request there, please comment on that request and I will close this one as duplicate.

Thanks again!

**Comment by josh-stein** [comment]
Duplicates/Enhances https://github.com/DigitaSecurity/DND-Issues/issues/3
