### ISSUE TITLE
Question: which version of the app to install? Digita Security or Objective-See?

### ISSUE THREAD

**Issue by JayBrown** [DigitaSecurity/DND-Issues#31]
This is all very confusing: both apps are free, but they have different version numbers, Objective-See is currently at v1.2.2, and Digita at v1.2.3, but I can't see any differences in functionality.

Which version do you suggest the user should install?

**Comment by josh-stein** [comment]
Jay, Thank you for your question. Your confusion is understandable. 
![screen shot 2018-08-15 at 8 35 34 am](https://user-images.githubusercontent.com/11893877/44148457-81f0158c-a066-11e8-8326-2f395a91722f.png)

We've attempted to address this question in the DND User Guide [FAQs](https://digitasecurity.com/donotdisturb/userguide/#faqs). A screen grab of the relevant section is also attached to this ticket.

As far as the version numbers are concerned -- there is no difference in functionality. We released a bug fix in an earlier version that was not individually released by Objective-See -- putting us one bug fix number ahead of them. We'll look to get back in sync to avoid this specific issue in the future.
