### ISSUE TITLE
1.0.1 doesn't pair

### ISSUE THREAD

**Issue by macMikey** [DigitaSecurity/DND-Issues#4]
Mobile fails connecting to server.  All seemed to work in 1.0.
Deleting mobile, reinstalling, and scanning qr can't get past register for notifications

**Comment by lukeshoberg** [comment]
Same experience. Pairing process hangs on iOS at Register for Notifications
Mac app doesn't show paired device on General tab. 
iOS app shows a paired device under Settings, if you "Test Device Pairing" that is successful. But pairing is clearly not successful and closing/opening lid generates no events on mobile

**Comment by josh-stein** [comment]
Backend was rebuilt for production (new certs) and the new beta was cutover. Requires a full uninstall of mac app, re-generation of qrc code and rescan via mobile app. Please let us know if this resolves the issue and thanks for your patience. 

#betapain

**Comment by lukeshoberg** [comment]
Ah - "full uninstall of Mac app" means deleting the contents of /Library/DigitaSecurity and reinstalling the app, rescanning qrc, etc. Working now, thanks!

**Comment by josh-stein** [comment]
Yah, did the "Uninstall" option from the installer not remove those contents?

**Comment by lukeshoberg** [comment]
Er, didn't use that button. No doubt it would have.

**Comment by macMikey** [comment]
Ah.  I missed the uninstall button.  Fixed.

**Comment by josh-stein** [comment]
Thanks!
