### ISSUE TITLE
Consider running app communication over TCP 443

### ISSUE THREAD

**Issue by lukeshoberg** [DigitaSecurity/DND-Issues#5]
To minimize the likelihood of app communication being blocked by default-deny firewalls, please consider moving network ports from TCP 8883 to TCP 443

**Comment by webframp** [comment]
Would like to see this since I think I might be experiencing this issue right now, pairing fails the "Connect to Server" test

**Comment by josh-stein** [comment]
See https://github.com/DigitaSecurity/DND-Issues/issues/24 for iOS equivalent ticket.
