### ISSUE TITLE
ios Aspect Ratio Only Phone

### ISSUE THREAD

**Issue by macMikey** [DigitaSecurity/DND-Issues#6]
Please generate a layout for ipads.  I tossed my iphone for an android, but still use my ipad constantly.  The screens on an ipad can be challenging.

**Comment by jon-djon** [comment]
We ended up releasing a universal app with iPad support since we are using auto-layout.  Please let us know if anything is not rendering well on an iPad.

**Comment by josh-stein** [comment]
Going to close this issue for now (was entered in beta), believing our build for a Universal Binary (eventually the released version) made this more acceptable, albeit not optimized for iPad. 

@macMikey Please let us know if there is a screen that is particularly challenging in the release build, or any other layout issues you may have.

**Comment by macMikey** [comment]
It's worked for me since the 1.0 release or whatever the release was that followed the report.  I'm on a 10.9 pro, or whatever the smaller pro is.  I rate it as "close enough, ship it".
